// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvbtIIiCPyqLYmqnu-c-9yLHqiH5MzGpM',
    appId: '1:490649772593:web:9467164fe157c6d872ab10',
    messagingSenderId: '490649772593',
    projectId: 'menu-36e8b',
    authDomain: 'menu-36e8b.firebaseapp.com',
    storageBucket: 'menu-36e8b.firebasestorage.app',
    measurementId: 'G-XXWVP502DM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZbcF0IzUbTkOxLfWofA1vn709kH-hYus',
    appId: '1:490649772593:android:62e14e2e1ef893fa72ab10',
    messagingSenderId: '490649772593',
    projectId: 'menu-36e8b',
    storageBucket: 'menu-36e8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPiihqfW2LfiHqpmzYvjN9LNIXUPwqTZU',
    appId: '1:490649772593:ios:0b08d2694da75ec772ab10',
    messagingSenderId: '490649772593',
    projectId: 'menu-36e8b',
    storageBucket: 'menu-36e8b.firebasestorage.app',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPiihqfW2LfiHqpmzYvjN9LNIXUPwqTZU',
    appId: '1:490649772593:ios:0b08d2694da75ec772ab10',
    messagingSenderId: '490649772593',
    projectId: 'menu-36e8b',
    storageBucket: 'menu-36e8b.firebasestorage.app',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvbtIIiCPyqLYmqnu-c-9yLHqiH5MzGpM',
    appId: '1:490649772593:web:42e9da1e537c6b8472ab10',
    messagingSenderId: '490649772593',
    projectId: 'menu-36e8b',
    authDomain: 'menu-36e8b.firebaseapp.com',
    storageBucket: 'menu-36e8b.firebasestorage.app',
    measurementId: 'G-0175RJT6QJ',
  );
}
